Repository gtb-team5/gtb-team5.github.io, pull requests merged in 2019-06, with the labels that each got.

#3 じこしょうかい
  index.html
Labels: help wanted

#2 自己紹介追加
  index.html
Labels: good first issue

#4 松尾が追記
  index.html
Labels: question

#5 タコ焼き食べたい
  index.html
Labels: documentation

#1 add sakamoto description
  index.html
Labels: bug
